---
# tasks file for ucsdlib.ansible-role-phantomjs
  - name: Download dependencies
    yum:
      name: "{{ item }}"
      state: latest
    with_items:
      - fontconfig
      - fontconfig-devel
      - freetype
      - freetype-devel
      - libstdc++

  - name: Is PhantomJS installed?
    stat:
      path: '{{ phantomjs_install_dir ~ "/" ~ phantomjs_version_dir ~ "/bin/phantomjs"  }}'
    register: phantomjs_bin

  - block:
    - name: Create install directory
      file:
        path: '{{ phantomjs_install_dir }}'
        state: directory

    - name: Download phantomjs
      get_url:
        url: '{{ phantomjs_download_uri }}'
        dest: '{{ phantomjs_download_dir }}/phantomjs.tar.gz'
        checksum: '{{ phantomjs_checksum_algorithm }}:{{ phantomjs_checksum }}'

    - name: Unpack phantomjs
      unarchive:
        src: '{{ phantomjs_download_dir }}/phantomjs.tar.gz'
        dest: '{{ phantomjs_install_dir }}'
        copy: no

    - name: Remove phantomjs download
      file:
        path: '{{ phantomjs_download_dir }}/phantomjs.tar.gz'
        state: absent

    - name: Ensure /usr/local/bin directory exists
      file:
        path: /usr/local/bin
        state: directory

    when: not phantomjs_bin.stat.exists

  - name: Create phantomjs symlink
    file:
      src: '{{ phantomjs_install_dir ~ "/" ~ phantomjs_version_dir ~ "/bin/phantomjs"  }}'
      dest: /usr/local/bin/phantomjs
      state: link

